/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhaoyuan_AsyncServletDemo_jni_CPPLibrary */

#ifndef _Included_com_zhaoyuan_AsyncServletDemo_jni_CPPLibrary
#define _Included_com_zhaoyuan_AsyncServletDemo_jni_CPPLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhaoyuan_AsyncServletDemo_jni_CPPLibrary
 * Method:    calc1
 * Signature: ([D[DZ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_zhaoyuan_AsyncServletDemo_jni_CPPLibrary_calc1
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
